### ISSUE TITLE
Add version_id to IDX_xxxx_RESOURCESLOGICAL_RESOURCE_ID index to avoid bad plans in Db2

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#1399]
**Is your feature request related to a problem? Please describe.**
The following query executed within the ADD_ANY_RESOURCE procedure was observed on one occasion to use completely the wrong index. This caused the average execution time to jump from 0.16ms to over 1500ms:

```
SET (?) = (SELECT resource_id FROM FHIRDATA.Observation_resources dr  WHERE dr.logical_resource_id = ?    AND dr.version_id = ?)
```

The bad access plan was:

```
| Index Scan: Name = FHIRDATA.OBSERVATION_RESOURCES_PRF_IN1 ID = 2
| | Regular Index (Not Clustered)
| | Index Columns:
| | | 1: MT_ID (Ascending)
| | | 2: RESOURCE_ID (Ascending)
| | | 3: LOGICAL_RESOURCE_ID (Include Column)
| | | 4: VERSION_ID (Include Column)
| | | 5: IS_DELETED (Include Column)
| #Columns = 1
```

Note: MT_ID is the tenant identifier, and is automatically included in every filter predicate as part of a row permission (row based access control) predicate.

**Describe the solution you'd like**
Add VERSION_ID to the definition of IDX_xxxx_RESOURCESLOGICAL_RESOURCE_ID. The index can also be unique, which should make it harder for the optimizer to ignore because stats would not be required for a cardinality estimate when picking the index.

CREATE UNIQUE INDEX IDX_xxxx_RESOURCES_LRV ON xxxx_RESOURCES (MT_ID, LOGICAL_RESOURCE_ID, VERSION_ID). 

**Describe alternatives you've considered**
No change, and live with the current risk of a bad plan being picked under unknown circumstances.

**Additional context**
Awaiting feedback from Db2 support ticket.

**Comment by lmsurpre** [comment]
@punktilious do you think this issue was specific to db2?  if so, I think we can close it now.

**Comment by punktilious** [comment]
Closing as this is no longer relevant.
