### ISSUE TITLE
Duplicate examples under fhir-examples json/ibm/minimal

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#1565]
**Is your feature request related to a problem? Please describe.**
Robin noticed that all of the minimal "Parameters" examples are duplicates.

Currently, we generate one instance per "choice type".  However, in the case of the minimal Parameters examples, these choice types aren't even required in the resource and so they are not present, leading to 50 copies of the same resource.

**Describe the solution you'd like**
The minimal example generator should be smarter.  It should only generate permutations of the resource for choice elements with a min cardinality of 1 or greater.

I think we could add a "minimal" flag to the private DataCreatorBase.getMaxChoiceCount helper method and then pass a value of true when its called from the MinimalDataCreator.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Patil2099** [comment]
I would love to work on this issue. Can I work on this? @lmsurpre

**Comment by prb112** [comment]
@Patil2099 we'd be happy to have you work on it.  Please let us know if you have any questions.

**Comment by prb112** [comment]
Posted a proposal after looking at the SHA256SUMs and seeing the broad number of files impacted.

**Comment by lmsurpre** [comment]
I snuck this one into my work on R4B.

**Comment by lmsurpre** [comment]
Its much better now, but here are still a couple resource type examples with identical content. Most notably, we have 49 minimal StructureMap examples that are all the same.  At the very least we could special-case this resource type and get down to 1.

**Comment by punktilious** [comment]
Some minimal examples are still the same e.g.
```
diff GuidanceResponse-1.json GuidanceResponse-2.json
```

Need some guidance on acceptance criteria.

**Comment by lmsurpre** [comment]
Ideally we'd investigate and remove those, but if its just ones and twos here and there I'm not too worried about it...probably not worth our time.
