### ISSUE TITLE
Add Db2 recommendations to performance and sizing reference guide

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#1890]
The performance and sizing reference guide covers PostgreSQL but the Db2 section is TBD.

**Comment by lmsurpre** [comment]
Now that we've removed our support for Db2, we should just remove this section.
@punktilious if its not done yet, can you do that as part of #3834 ?

**Comment by lmsurpre** [comment]
I confirmed this change is already included in #3835 and so I've moved this one to Review
