### ISSUE TITLE
Investigate cache stats / cache management

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#2733]
**Is your feature request related to a problem? Please describe.**
In past efforts, we moved all the internal caches to Caffiene which includes some mechanisms for getting cache statistics.

**Describe the solution you'd like**
We should use those.

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
Would be good to try answering how this changes with scale.  How much cache memory we need for a particular workload, etc.

**Comment by prb112** [comment]
[] Enumerate the Caches that aren't in the stats

**Comment by prb112** [comment]
# fhir-core
fhir-core/src/main/java/com/ibm/fhir/core/TenantSpecificFileBasedCache.java
-- We could implement a cache with this... however, it's pretty low level and we might not want to. 

# fhir-model? cache? 
fhir-model/src/main/java/com/ibm/fhir/model/constraint/spi/AbstractConstraintProvider.java
- I think the caching is at a higher level

fhir-model/src/main/java/com/ibm/fhir/model/lang/util/LanguageRegistry.java
fhir-model/src/main/java/com/ibm/fhir/model/lang/util/LanguageRegistryUtil.java
- I don't think we need to have a tenant specific cache for this? 

# fhir-path
fhir-path/src/main/java/com/ibm/fhir/path/function/registry/FHIRPathFunctionRegistry.java

# fhir-search
/fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
/fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentCache.java
/fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentUtil.java
/fhir-search/src/main/java/com/ibm/fhir/search/compartment/ResourceCompartmentCache.java
/fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
/fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
/fhir-search/src/main/java/com/ibm/fhir/search/parameters/cache/TenantSpecificSearchParameterCache.java (might take somethought)
- caches that could move to caffeine

# fhir-profile
fhir-profile/src/main/java/com/ibm/fhir/profile/ProfileSupport.java
- Lee added 

# fhir-registry
/fhir-registry/src/main/java/com/ibm/fhir/registry/util/PackageRegistryResourceProvider.java
- should this be in caffeine even though it's loaded once and available across the server? do we want this to be multitenant

# fhir-notification-websocket
/notification/fhir-notification-websocket/src/main/java/com/ibm/fhir/notification/websocket/impl/FHIRNotificationServiceEndpoint.java
- uses concurrent hashmap (and it's truly not tenant aware leading to leakage, do we want to make it tenant aware?)

# fhir-server
/fhir-server/src/main/java/com/ibm/fhir/server/operation/FHIROperationRegistry.java
- registry should it be enabled
/fhir-server/src/main/java/com/ibm/fhir/server/registry/ServerRegistryResourceProvider.java
/fhir-server/src/main/java/com/ibm/fhir/server/resolve/ServerResolveFunction.java
- already cache enabled with caffeine

# fhir-term
/term/fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
- already enabled with caffeine


# fhir-persistence-jdbc
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/CommonTokenValuesCacheImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/FHIRPersistenceJDBCCacheUtil.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/FHIRPersistenceJDBCTenantCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/IdNameCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/LRUCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/cache/NameIdCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/CodeSystemDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchPayloadsForIdsDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/JDBCIdentityCacheImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterNameDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceReferenceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/RetrieveIndexDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/TransactionDataImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/db2/Db2ResourceReferenceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceReferenceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQuery.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchQueryRenderer.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchSortQuery.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchWholeSystemFilterQuery.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/domain/SearchWholeSystemQuery.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/CompositeParmVal.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/ParameterTransactionDataImpl.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceReferenceDAO.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CacheUtil.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CodeSystemsCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ParameterNamesCache.java
fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/ResourceTypesCache.java
- above caches need to be reconciled

**Comment by prb112** [comment]
@lmsurpre do you want me to open downstream issues?

**Comment by prb112** [comment]
Met with Lee 
- further analysis running on CDT
- Paul mentioned to Lee - candidates are jdbc,server,search are candidates for using caffeine.
