### ISSUE TITLE
Import from S3

### ISSUE THREAD

**Issue by zaus71** [LinuxForHealth/FHIR#2856]
I pulled the current docker image and want to use PostMan to import from an S3 store. I used this body:

{
    "resourceType": "Parameters",
    "id": "30321130-5032-49fb-be54-9b8b82b2445a",
    "parameter": [
        {
            "name": "inputFormat",
            "valueString": "application/fhir+ndjson"
        },
        {
            "name": "inputSource",
            "valueUri": "https://<mybucket>.s3.eu-central-1.amazonaws.com"
        },
        {
            "name": "input",
            "part": [
                {
                    "name": "type",
                    "valueString": "Patient"
                },
                {
                    "name": "url",
                    "valueUrl": "patient.ndjson"
                }
            ]
        },
        {
            "name": "storageDetail",
            "valueString": "aws-s3"
        }
    ]
}

But get this error:

{
    "resourceType": "OperationOutcome",
    "id": "ac-11-0-2-d16cc264-bb10-457b-be49-50c8aa010f01",
    "issue": [
        {
            "severity": "fatal",
            "code": "invalid",
            "details": {
                "text": "File: Configuration not set to import from storageDetail 'default'"
            },
            "expression": [
                "<empty>"
            ]
        }
    ]
}

What am I doing wrong? Why does this error message come from the file importer?

**Comment by prb112** [comment]
Great - best wishes, Paul
