### ISSUE TITLE
clarify use of the `--tenant-key` option in fhir-persistence-schema

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3248]
**Describe the bug**
The usage info says it accepts a `--tenant-key` and we have logic in place for this option in the cli argument parsing switch construct.

However, in both `addTenantKey()` and `allocateTenant()`, we're overriding the tenantKey value unless there was a `--tenant-key-file` argument passed.

I believe `--tenant-key` is only intended to work with the `--test-tenant` action, but thats not too clear from the docs (either usage info printed by `--help` or what we have in the readme at https://github.com/IBM/FHIR/tree/main/fhir-persistence-schema#list-of-ibm-fhir-server-persistence-schema-tool-flags)

**Environment**
main

**To Reproduce**
1. setup db2
2. run an allocate-tenant action and pass a tenant-key value via the `--tenant-key` argument
   ```
   --prop-file db2.properties
   --schema-name FHIRDATA
   --allocate-tenant default
   --tenant-key UldxYnBVdFNjbTY5RnRoSHZrQTVTKzdwaEN2UDlBS1dXemZ6Y1JPRlFWcz0=
   --pool-size 1
   ```

Note that the `--tenant-key` option is ignored and the tool assigns a new tenantKey instead.

**Expected behavior**
I think either we should support the `--tenant-key` option on allocateTenant or we should more clearly document which flags are valid for which actions.

**Additional context**
In general, the fhir-persistence-schema tool has a lot of options that can make it difficult to use / understand.
I thought we had a placeholder to consider what we could do to make the options cleaner / easier / more obvious for users, but I think I must have just been thinking of #3072

**Comment by prb112** [comment]
The logic in issue #990 and PR https://github.com/IBM/FHIR/pull/996/files#diff-b4577e1635a5c980b9e41f30be0c6abcbf3fe5e6915b118fd319963bdac70a78R852-R858

Was to check if the tenant-key-file exists, else generate. 
I agree with you that it should be externally set.

**Comment by lmsurpre** [comment]
I actually like that we will generate one for you.  My concern is mostly with managing the many options for the schema tool.  Certain flags only work with certain actions.  Some actions can be combined and some cannot.  I'm not sure how to best document it all, but I think we could do better.

**Comment by lmsurpre** [comment]
we should probably also clarify the relationship between what the tool outputs for tenant key and how to pass it back in.  e.g. from the docs:
```
--tenant-key "<the-base64-tenant-key>"
```

answer:  the output is already base64-encoded, no need to re-encode

**Comment by lmsurpre** [comment]
this entire flag is going away as part of #3803
