### ISSUE TITLE
[fhir-client] Document/support setting the fhirVersion mime-type parameter on requests

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3256]
**Is your feature request related to a problem? Please describe.**
From https://hl7.org/fhir/http.html#version-parameter
> This parameter can be used anywhere that the FHIR Mime type is used. When used in an HTTP request, the version parameter may be used on either the Content-Type header, or the Accept header, or both, and applies to the entire interaction

For R4B, via https://github.com/IBM/FHIR/issues/3192 and https://github.com/IBM/FHIR/issues/3242, we're gonna let this parameter drive server behavior, so we definitely need a way to set it from the client.

**Describe the solution you'd like**
1. if not supported already, add a config property to set the default value across all requests
2. document how to set it

**Describe alternatives you've considered**
Make it possible to set on a per-request basis

**Acceptance Criteria**

1.  
   GIVEN a client with `fhirclient.default.mimetype = application/fhir+json; fhirVersion=4.0`
   WHEN the request is made to the server
   THEN any applicable Accept or Content-Type header values have the fhirVersion mime type parameter set to 4.0

1.  
   GIVEN a client with `fhirclient.default.mimetype = application/fhir+json; fhirVersion=4.3` (the default) 
   WHEN the request is made to the server
   THEN any applicable Accept or Content-Type header values have the fhirVersion mime type parameter set to 4.3

**Additional context**

**Comment by lmsurpre** [comment]
It turns out we already support setting the default FHIR version from fhir-client.
I'm not sure how commonly we'd need to set the fhirVersion on a per-request basis, and so I'm updating the description and acceptance criteria to remove that part of it.

If needed, that can be a separate issue.

**Comment by punktilious** [comment]
Confirmed that when setting 
```
fhirclient.default.mimetype = application/fhir+json; fhirVersion=4.3
```

On the server side we see:
```
[25/08/2022, 11:31:33:934 UTC] 0000002a FHIRHttpServl 3   getHeaders("Content-Type") : [application/fhir+json;fhirversion=4.3]
[25/08/2022, 11:31:33:934 UTC] 0000002a FHIRHttpServl 3   getHeaders("Accept") : [application/fhir+json; fhirVersion=4.3]
```

and when setting
```
fhirclient.default.mimetype = application/fhir+json; fhirVersion=4.0
```

```
[25/08/2022, 12:06:12:611 UTC] 00000024 FHIRHttpServl 3   getHeaders("Content-Type") : [application/fhir+json;fhirversion=4.0]
[25/08/2022, 12:06:12:611 UTC] 00000024 FHIRHttpServl 3   getHeaders("Accept") : [application/fhir+json; fhirVersion=4.0]
```

It is noted that for Content-Type, the fhirVersion header value gets lower-cased to become `fhirversion`, but these parameters are case-insensitive according to the spec and the MediaType implementation.
