### ISSUE TITLE
documentation for transforming exported ndjson to parquet with spark

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3372]
> I think we should remove this feature and replace it with documentation that clearly shows how to convert the exported NDJSON to Parquet using spark (maybe a blog post?)

this piece of it is not done yet and I think we should do it either for this one or in a new related task

_Originally posted by @lmsurpre in https://github.com/IBM/FHIR/issues/3156#issuecomment-1025874476_

**Comment by punktilious** [comment]
I read through the post again and it seems reasonable. I think this one should be OK to just close.
