### ISSUE TITLE
Add experimental support for Citus

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3437]
**Is your feature request related to a problem? Please describe.**
Citus is a distributed database extension for PostgreSQL.

Add distribution/replication information to the schema so that this metadata can be applied when the tables are created. Filter the creation of foreign key relationships according to the distribution rules.

**Describe the solution you'd like**
The schema tool should contain support for Citus databases.

**Describe alternatives you've considered**
Apply the Citus logic manually after the schema is created.

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
Does not support migration from an earlier version. The first Citus install must be FHIR schema version V0026.

**Comment by lmsurpre** [comment]
Robin ran the fhir-server-test integration tests against a server configured with the citus backend and all tests were passed
