### ISSUE TITLE
update CodeGenerator to ensure unique constraint ids for bindings

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3474]
**Is your feature request related to a problem? Please describe.**
We were having an issue with this constraint from US Core 4.0: http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-provenance.html#constraints

For a moment, I was confused by the fact that our model has a different constraint with the same constraint id:  https://github.com/IBM/FHIR/blob/main/fhir-model/src/main/java/com/ibm/fhir/model/resource/Provenance.java#L68

**Describe the solution you'd like**
I think the `provenance-1` key is generated by us from our CodeGenerator.
Assuming thats right, I think we should generate something more unique that is less likely to conflict with a constraint key that is added in an IG.
My suggestion is to use a `binding-` prefix, so the key we generate will be like `binding-provenance-1` (or `provenance-binding-1`... whichever we want)... this has the added benefit of making it very clear that this is a binding constraint (vs. an 'invariant' defined in the core spec).

**Describe alternatives you've considered**

**Acceptance Criteria**

1. run `org.linuxforhealth.fhir.profile.test.ConstraintGeneratorTest` (or a variant of it)
2. confirm that no two constraints have the same constraint id and that the generated constraint ids do not overlap the base spec constraint ids

**Additional context**

**Comment by lmsurpre** [comment]
I think this one is already addressed in main.

**Comment by punktilious** [comment]
@lmsurpre currently in main I still see `provenance-1:

https://github.com/LinuxForHealth/FHIR/blob/main/fhir-model/src/main/java/org/linuxforhealth/fhir/model/resource/Provenance.java
```
@Constraint(
    id = "provenance-1",
    level = "Warning",
    location = "(base)",
    description = "SHALL, if possible, contain a code from value set http://hl7.org/fhir/ValueSet/provenance-activity-type",
    expression = "activity.exists() implies (activity.memberOf('http://hl7.org/fhir/ValueSet/provenance-activity-type', 'extensible'))",
    source = "http://hl7.org/fhir/StructureDefinition/Provenance",
    generated = true
)
```

**Comment by lmsurpre** [comment]
Right, the issue here was that we were generating a constraint with the same id.  I've updated the description with some acceptance criteria / QA hints for how it could be tested.
