### ISSUE TITLE
US Core contains invalid fhirpath expressions

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3490]
**Is your feature request related to a problem? Please describe.**
2 of the fhirpath expressions in us core 4.0 have issues with repeating elements:
* Condition: https://jira.hl7.org/browse/FHIR-36336
* Provenance: https://jira.hl7.org/browse/FHIR-36328

**Describe the solution you'd like**
We should patch the fhirpath expressions so that they work properly

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN a server configured with our us-core jar
    AND a Condition resource with multiple category elements
    AND it claims conformance to http://hl7.org/fhir/us/core/StructureDefinition/us-core-condition
   WHEN create or $validate is called with that resource
   THEN it either succeeds or fails with a client error (no server error)

1.  
   GIVEN a server configured with our us-core jar
    AND a Provenance resource with multiple agent elements (and at least one with agent.onBehalfOf)
    AND it claims conformance to http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance
   WHEN create or $validate is called with that resource
   THEN it either succeeds or fails with a client error (no server error)

**Additional context**

**Comment by d0roppe** [comment]
verified that with both Condition and Provenance work according to the acceptance criteria. Closing issue
