### ISSUE TITLE
Populate "path" property in FHIRPathNode implementations representing system values

### ISSUE THREAD

**Issue by jarrettranderson** [LinuxForHealth/FHIR#3619]
**Is your feature request related to a problem? Please describe.**
We have a requirement to remove the "id" property from certain elements of a resource.  Consistent with other planned operations, we would find the targets using a FHIRPath expression and then remove them using FHIRPathUtil.delete().  FHIRPathUtil.delete() requires the path to the target, but the path() method returns null for FHIRPathStringValue objects returned from the FHIRPath evaluation.

**Describe the solution you'd like**
The path() method in FHIRPathStringValue objects and probably other FHIRPathSystemValue implementations should return the path to the node like it does for other implementations of FHIRPathNode.

**Describe alternatives you've considered**
For this particular scenario, we could use FHIRPath to find all the Element type objects in the tree and check each of them to see if the "id" value is populated.  We would then update the parent object in a different manner.

**Acceptance Criteria**
1.  
   GIVEN [a FHIRPath expression that targets "id" or another system value field, such as "descendants().select(id)"]
     AND [EvaluationContext evaluationContext = new EvaluationContext(some-resource)]
   WHEN [FHIRPathEvaluator.evaluator().evaluate(evaluationContext, fhir-path-expression]
   THEN [for each object returned, path() is non-null]

**Additional context**

**Comment by lmsurpre** [comment]
Info for executing the fhir-path cli jar can be found at https://github.com/IBM/FHIR/tree/main/fhir-path

**Comment by lmsurpre** [comment]
Per the above I posted the following resource:
```
{
  "resourceType": "Patient",
  "id": "{{patient}}",
  "language": "en",
	"text": {
		"status": "empty",
		"div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Lee (1234)</div>"
	},
  "identifier": [{
    "use": "usual",
		"_use": {
			"id": "my-primitive-extension",
			"extension": [{
				"url": "http://example.com/primitive-extension",
				"valueString": "test1"
			}]
		},
		"system": "https://example.com",
		"value": "1234"
  }],
	"name": [{
		"given": ["Lee"],
		"_given": [{
			"id": "my-repeat-primitive-extension",
			"extension": [{
				"url": "http://example.com/primitive-extension",
				"valueString": "test2"
			}]
		}]
	}],
  "active": true
}
```

Then I removed the `Patient.identifier.use.id` element via a patch like this:
```
{
	"resourceType": "Parameters",
	"parameter": [
		{
			"name": "operation",
			"part": [
				{
					"name": "type",
					"valueCode": "delete" 
				},
				{
					"name": "path",
					"valueString": "Patient.identifier.use.id"
				}
			]
		}
	]
}
```

@d0roppe feel free to do some related testing

**Comment by lmsurpre** [comment]
seems to be working
