### ISSUE TITLE
Support for US Core 5.0

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3641]
US Core 5.0.0 was recently published:  https://hl7.org/fhir/us/core/
We should add that to our prepackaged support in fhir-ig-us-core

**Comment by lmsurpre** [comment]
Hit #3646 which is currently blocking this upgrade.  Since the constraint in question is just a "best practice" one (and not an "validity" one), I'm thinking to use our SPI to avoid firing this constraint for now.  Then we can circle back up and implement the `repeat` function sometime later.

**Comment by punktilious** [comment]
QA for #3646 demonstrates support for US Core 5.0.0, so closing this too.
