### ISSUE TITLE
Update to PDex Drug Formulary 1.1.0

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3652]
**Is your feature request related to a problem? Please describe.**
PDex Drug Formulary 1.1.0 was published last fall... its time we add that to our fhir-ig-pdex-formulary module.

**Describe the solution you'd like**
Add 1.1.0 alongside 1.0.1 ...similar to #3651 .

We should also move the corresponding examples from fhir-examples down to src/test/resources/examples/100 and add the new examples alongside those in a 110 directory.

**Describe alternatives you've considered**
Replace 1.0.1 with 1.1.0

**Acceptance Criteria**

1.  
   GIVEN the fhir-ig-davinci-pdex-formulary jar is in userlib
   WHEN a resource is validated against an applicable profile with no version suffix (or specifies a version of 1.1.0)
   THEN validation uses the artifacts from PDex Drug Formulary 1.1.0

1.  
   GIVEN the fhir-ig-davinci-pdex-formulary jar is in userlib
   WHEN a resource is validated against an applicable profile with a version id of 1.0.1
   THEN validation uses the artifacts from PDex Drug Formulary 1.0.1

**Additional context**

**Comment by lmsurpre** [comment]
Unfortunately, PDEX Drug Formulary 1.1.0 is not backwards compatible with version 1.0.1.

Currently, when the IBM FHIR Server sees an extension, it looks up the corresponding extension definition in the registry.  This happens outside of any profile validation.

However, because extension urls are never versioned, this means that we'll always look up the latest definition.  This makes us quite sensitive to extension definitions that change over time.

In PDEX US Drug Formulary 1.1.0, the following extension values have changed from type `string` to type `uri`:
* http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-MarketingURL-extension
* http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-SummaryURL-extension
* http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension
* http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-EmailPlanContact-extension

To further complicate matters, the display names in the `http://hl7.org/fhir/us/davinci-drug-formulary/ValueSet/CopayOptionVS` CodeSystem have changed as well. This CodeSystem is referenced from `http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-DrugTierDefinition-extension`.

These breaking changes mean that a valid 1.0.1 instance will likely be invalid in version 1.1.0 and, because we check extensions separate from profile validation, such instances will fail our validation just by having the 1.1.0 versions in the registry.

For this reason, I'm thinking that maybe we should split version 1.1.0 into a separate jar from 1.0.1 (or avoid packaging it altogether).
The alternative would be to try making our Validator more intelligent:  if an extension url is mentioned in the profile, and the profile indicates a particular version of that extension, then only check against that version (and not the latest).  This will be tricky because, as mentioned above, the extension validation happens independent of profile validation today.

**Comment by lmsurpre** [comment]
I ended up implementing this:
> if an extension url is mentioned in the profile, and the profile indicates a particular version of that extension, then only check against that version

**Comment by PrasannaHegde1** [comment]
Tried with a sample resource with a profile version id of 1.0.1, changed the MarketingURL-extension, SummaryURL-extension,  FormularyURL-extension, EmailPlanContact-extension from type string to type uri and the validation returned errors. 

````json
{
    "resourceType": "OperationOutcome",
    "id": "Error",
    "text": {
        "status": "additional",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>ERROR</p></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invariant",
            "details": {
                "text": "generated-usdf-CoveragePlan~List.extension<http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension>: Constraint violation: extension('http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension').exists() implies (extension('http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension').count() = 1 and extension('http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension').all(conformsTo('http://hl7.org/fhir/us/davinci-drug-formulary/StructureDefinition/usdf-FormularyURL-extension|1.0.1')))"
            },
            "diagnostics": "Caused by: [[expression: value.as(string).exists(), result: false, location: List.extension[2]]]",
            "expression": [
                "List"
            ]
        },
        {
            "severity": "information",
            "code": "invariant",
            "details": {
                "text": "generated-usdf-FormularyURL-extension-2: Constraint violation: value.as(string).exists()"
            },
            "expression": [
                "List.extension[2]"
            ]
        }
    ]
}
````


Tried with a sample resource with a profile version id of 1.0.1 with valid MarketingURL-extension, SummaryURL-extension,  FormularyURL-extension, EmailPlanContact-extension types(type string) and the validation was successful.
````json
{
    "resourceType": "OperationOutcome",
    "id": "NoError",
    "text": {
        "status": "additional",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>No error</p></div>"
    },
    "issue": [
        {
            "severity": "information",
            "code": "informational",
            "details": {
                "text": "All OK"
            }
        }
    ]
}
````


Tried with a sample resource with a profile version id of 1.0.1 with invalid code display names for DrugTierCS, CoinsuranceOptionCS, CopayOptionCS, PharmacyTypeCS for version 1.0.1 and the validation returned "code-invalid".
````json
{
    "resourceType": "OperationOutcome",
    "id": "NoError",
    "text": {
        "status": "additional",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>No error</p></div>"
    },
    "issue": [
        {
            "severity": "information",
            "code": "code-invalid",
            "details": {
                "text": "generated-usdf-DrugTierDefinition-extension-1: A code in this element must be from the specified value set 'http://hl7.org/fhir/us/davinci-drug-formulary/ValueSet/DrugTierVS|1.0.1' if possible"
            },
            "expression": [
                "List.extension[0].extension[0].value"
            ]
        }
    ]
}
````

Tried with a sample resource with a profile version id of 1.0.1 with valid code display names for DrugTierCS, CoinsuranceOptionCS, CopayOptionCS, PharmacyTypeCS for version 1.0.1 and the validation was successful.
````json
{
    "resourceType": "OperationOutcome",
    "id": "NoError",
    "text": {
        "status": "additional",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p>No error</p></div>"
    },
    "issue": [
        {
            "severity": "information",
            "code": "informational",
            "details": {
                "text": "All OK"
            }
        }
    ]
}
````
