### ISSUE TITLE
Use resolve() function in Expression Profile

### ISSUE THREAD

**Issue by APicchio** [LinuxForHealth/FHIR#3663]
I’m trying to use the resolve function to verify that the generalPractitioner presents in the Patient resource is an instance of the Practitioner resource.

Unfortunately, there isn’t a “IBM Fhir for dummy”! and I’m sure I’m doing something wrong.
As reported in one issue, in the file “fhir-server-config.json” the variable “serverResolveFunctionEnabled" is set to true.

In the Patient resource, the generalPractitioner is valorized with an “id” that is not present as Practitoner. 
"generalPractitioner":[{
                        "reference":"https://laptop-apicchiotti:9443/fhir-server/api/v4/Practitioner/123",
                        "type":"Practitioner"
                    }]",
In the profile I did two different tests.
-	“Patient.generalPractitioner.resolve() is Practitioner”
The validation doesn’t show any error.
-	“Expression” is valorized with “Patient.generalPractitioner.is(FHIR.generalPractitioner)” 
The validation shows error also when the id is present as Practitioner.

Thank you for you patient and support,
Alex

**Comment by lmsurpre** [comment]
> Patient.generalPractitioner.is(FHIR.generalPractitioner)

This expression doesn't look valid to me.  did you mean `Patient.generalPractitioner.is(FHIR.Practitioner)`?  I'd expect that to behave the same as `Patient.generalPractitioner.resolve() is Practitioner`


As for why our validator thinks that its valid, I think that is working as designed:  we don't treat broken references as invalid.
This is similar to 'referential integrity' in database terms, except that in FHIR a reference can be either relative or absolute.
In such cases, we'll only reject the request if the reference looks like its of the wrong type (e.g. if the reference was like `Medication/123` we'd call that invalid).
Now, I could see someone wanting to consider that invalid, so if you'd like to make this a feature request for that design change, do let me know.

Alternatively, you could verify that this resource actually exists by either:
A. Overriding our 'resolve()' function in the FHIRPathFunctionRegistry; or
B. Implementing a [FHIRPersistenceInterceptor](https://ibm.github.io/FHIR/guides/FHIRServerUsersGuide#43-persistence-interceptors) that looks for incoming Patient resources, does a read of the referenced generalPractitioner, and throws if that doesn't exist.
C. doing something like B but from the client or a gateway

**Comment by APicchio** [comment]
>>if you'd like to make this a feature request for that design change, do let me know.
For me it could be an useful feature! 
In the meanwhile I can use the FHIRPersistenceInterceptor that I'm already using for other situations.

I confirm that "Patient.generalPractitioner.is(FHIR.Practitioner)" works as "Patient.generalPractitioner.resolve() is Practitioner". 

Thanks,
Alex

**Comment by lmsurpre** [comment]
We opened #4004 for the feature request part of this one.
