### ISSUE TITLE
Refactor parameter persistence to use fhir-remote-index backend

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3664]
**Is your feature request related to a problem? Please describe.**
fhir-remote-index uses a new implementation to collect parameter values, handle resolution of all the lookup values, and then persist the values using bulk inserts.

This code should be refactored into a separate project allowing it to be used in the fhir-persistence-jdbc layer to synchronously insert the parameter values. This also allows *all* the parameter values to be batched before processing, which should lead to an improvement in performance.

**Comment by lmsurpre** [comment]
@punktilious this work is now in main, correct?

**Comment by lmsurpre** [comment]
The bulk of this is covered through fhir server tests.
Maybe eyeball one resource that has at least one parameter of each type (system-level and instance-level).  Also a combination of a remote reference and local references?

**Comment by lmsurpre** [comment]
We reviewed some of the search parameter tables after ingestion and everything seems ok.
