### ISSUE TITLE
The application or context root for this request has not been found: /openapi/ui/

### ISSUE THREAD

**Issue by darmawan01** [LinuxForHealth/FHIR#3691]
Help!

Run the fhir server using demo , no error but when access the swagger got the `The application or context root for this request has not been found: /openapi/ui/`

Accessing using http://localhost:9080/openapi/ui

Thanks for help

**Comment by lmsurpre** [comment]
I confirmed that this is working just fine for me from `main`.
Did you check the logs?
```
docker compose logs --tail [numberOfRows]
```
