### ISSUE TITLE
Add remote-index support for Db2

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3720]
**Is your feature request related to a problem? Please describe.**
Current the fhir-remote-index project supports only PostgreSQL.

**Describe the solution you'd like**
Add Db2 support if needed.

**Describe alternatives you've considered**
No not support the remote index feature for Db2.

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
Alternatively, we can close this one if we remove db2 support first:  #3676

**Comment by lmsurpre** [comment]
we dropped db2 support so this one is no longer valid
