### ISSUE TITLE
fhir-bucket reindex driver must support force option

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3731]
**Describe the bug**
When reindexing, the server checks the hash of the extracted parameter values with the value currently stored in the database. If they match, the reindex is skipped. Unfortunately this means that reindex is skipped when we've changed the parameter storage schema (as we did for schema V0027). The reindex operation supports a "force" parameter which overrides the hash check. However, this option currently isn't passed when using fhir-bucket to drive the reindex.

**Environment**
Which version of IBM FHIR Server? 5.0.0-SNAPSHOT

**To Reproduce**
1. Install 4.11.1
2. Load data
3. Perform a search using a reference field
4. Upgrade to 5.0.0 (schema V0028)
5. Run reindex
6. See searches using references fail to retrieve data

**Expected behavior**
fhir-bucket needs to support a `--reindex-force` option and if true, will pass the force parameter value in the reindex request.

The fhir-bucket README.md should also be updated with the new option.

**Additional context**
We may also want to consider including the current schema version in the parameter hash calculation. This would make the reindex automatic when we change the schema version. But this a little more complicated, because not all schema changes require a reindex.

**Comment by lmsurpre** [comment]
Robin has been using this a lot and we see the log output as proof
