### ISSUE TITLE
Conditional PATCH returns NullPointerException

### ISSUE THREAD

**Issue by renom** [LinuxForHealth/FHIR#3773]
Request: `PATCH /fhir-server/api/v4/Patient?_id={existing_id}`

Response:
```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "code": "exception",
            "details": {
                "text": "NullPointerException: &lt;null message&gt;"
            }
        }
    ]
}
```
There's the same error when different filters are passed.

**Comment by lmsurpre** [comment]
I was able to reproduce it and captured the following stack trace:
```[INFO] FHIRResource  E   An unexpected exception occurred while processing the request
[INFO]                                  java.lang.NullPointerException: Cannot invoke "com.ibm.fhir.model.resource.Resource.getId()" because "newResource" is null
[INFO] 	at com.ibm.fhir.server.util.FHIRRestHelper.doUpdateMeta(FHIRRestHelper.java:619)
[INFO] 	at com.ibm.fhir.server.util.FHIRRestHelper.doPatchOrUpdate(FHIRRestHelper.java:484)
[INFO] 	at com.ibm.fhir.server.util.FHIRRestHelper.doPatch(FHIRRestHelper.java:438)
[INFO] 	at com.ibm.fhir.server.resources.Patch.conditionalPatch(Patch.java:276)```

**Comment by lmsurpre** [comment]
QA: test both JSONPatch and FHIRPathPatch and confirm no NPE

**Comment by PrasannaHegde1** [comment]
tried condition PATCH with both JSONPatch and FHIRPathPatch with below requests.
JSONPatch:
Request: PATCH /fhir-server/api/v4/Patient?name=Dave
Requesy body :  [{ "op": "add", "path": "/gender", "value": "male" }]
Response : 200 OK. No null pointer exception observed.
![3733_json_patch](https://user-images.githubusercontent.com/109784806/183393273-28686b9c-1805-48d7-8e57-1d4eb9d20ba9.JPG)


FHIRPathPatch:
Request: PATCH /fhir-server/api/v4/Patient?name=Dave
Requesy body :  
{
    "resourceType": "Parameters",
    "id": "test",
    "parameter": [
        {
            "name": "operation",
            "part": [
                {
                    "name": "type",
                    "valueCode": "replace"
                },
                {
                    "name": "path",
                    "valueString": "Patient.gender"
                },
                {
                    "name": "value",
                    "valueCode": "male"
                }
            ]
        }
    ]
}

Response : 200 OK. No null pointer exception observed.
![3733_fhirpath_patch](https://user-images.githubusercontent.com/109784806/183393314-77d35f3e-9dfb-406d-bda0-e79e07fcf021.JPG)
