### ISSUE TITLE
Remove mention of Db2 from documentation

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3834]
**Describe the bug**
LinuxForHealth FHIR Server Release 5.0.0 will not support Db2. Remove remaining references to Db2 from documents, including deleting DB2OnCloudSetup.md.

**Environment**
Which version of IBM FHIR Server? 5.0.0-SNAPSHOT

**Comment by lmsurpre** [comment]
the doc updates are in
