### ISSUE TITLE
Release docker images to github packages (ghcr.io)

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3845]
**Is your feature request related to a problem? Please describe.**
For IBM FHIR Server, we pushed our docker images to DockerHub under the organization `ibmcom`.

The LinuxForHealth project has its own organization on DockerHub at https://hub.docker.com/u/linuxforhealth.
However, DockerHub has some rather significant limitations for us and alternative image hosting is readily available.

I discussed it with @dixonwhitmire and we decided to use the GitHub Container Registry for our images going forward.
This will mean a longer image path (`ghcr.io/linuxforhealth/fhir-server` instead of just `linuxforhealth/fhir-server`) but we think its still reasonable.

**Describe the solution you'd like**
Update our automation

Question:  Will github packages let us update an image thats already been pushed.  We do that today to ensure that the base OS stays up-to-date with security fixes.  I assume it will allow that since its pretty common practice.

**Describe alternatives you've considered**
Continue pushing to DockerHub (under linuxforhealth)

**Acceptance Criteria**

1.  
   GIVEN [a precondition]
    AND [another precondition]
   WHEN [test step]
    AND [test step]
   THEN [verification step]
    AND [verification step]

**Additional context**
At least two workflows need updating:
* release.yml
* rebuild.yml

**Comment by punktilious** [comment]
Confirmed that the docker image exists:

```
REPOSITORY                                   TAG                                      IMAGE ID      CREATED        SIZE
ghcr.io/linuxforhealth/fhir-server           latest                                   415b2d5018c8  11 days ago    1.26 GB
```
Pulled it, ran it with bootstrapping enabled and was able to POST a new resource.
