### ISSUE TITLE
More ibm -> linuxforhealth renaming

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3855]
**Is your feature request related to a problem? Please describe.**
There's a few more code-related locations that we should migrate before our 5.0
* the 'ibm' directories under fhir-examples (json and xml)
* `ibm-*` prefixes for internal search parameters
* `ibm.com` URIs in extension URLs

**Describe the solution you'd like**
No more references to IBM in code artifacts

**Describe alternatives you've considered**

**Acceptance Criteria**

References to 'ibm' from the codebase are reduced to a reasonable set.  "reasonable" here is up for interpretation, but should not include ibm.com urls in data

**Additional context**

**Comment by punktilious** [comment]
QA:
1. There are no ibm directories under fhir-examples
2. There are no unnecessary instances of the prefix `ibm-` in the codebase
3. There is one unnecessary instance of `ibm.com` in the codebase.

However, for item (3) in SearchExtensionsTest:
```
                .extension(Extension.builder()
                        .url(EXTENSION_BASE_URL + "favorite-uri")
                        .value(uri("http://www.ibm.com"))
                        .build())
``` 
as this is just a unit test, there is no leak of this value in the product runtime. The test can be cleaned up at a convenient time in the future.
