### ISSUE TITLE
Update release process to post to the new sonatype OSS hosting

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3885]
**Is your feature request related to a problem? Please describe.**
I opened the request for the "org.linuxforhealth" group id at https://issues.sonatype.org/browse/OSSRH-83433
and that should be all set now:

> Congratulations! Welcome to the Central Repository!
> org.linuxforhealth has been prepared, now user(s) lmsurprenant can:
> Publish snapshot and release artifacts to s01.oss.sonatype.org

Now its time to update our release automation.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Acceptance Criteria**

1.  
   GIVEN a release candidate
   WHEN you push a release tag (e.g. 5.0.0)
   THEN if the tagged version passes all of the tests, the java artifacts should be uploaded to s01.oss.sonatype.org
    AND can be published to maven central from there

**Additional context**
Should be done together with the updates to the linux container image release under #3845

**Comment by punktilious** [comment]
@lmsurpre how do you propose we QA this one?

**Comment by lmsurpre** [comment]
I confirm that this is working now.

However, there's one step in particular thats been flaky:  uploading the fhir-install zip to OSSRH

For RC1, it took 5 tries.
For RC2, it took 2 tries.

I opened https://issues.sonatype.org/browse/OSSRH-83767 for it, but if it continues to happen we might want to either:
A. add special retry logic to our release scripts so that we don't need to "start over" each time it fails to upload; or
B. stop putting this particular artifact in central (we'd still have it in GitHub Releases tab, just not maven central).

Notably, this zip installer has gotten quite large (almost 500 MB!).  Most of that is the liberty zip that we embed in it.
We definitely have options for slimming that down and I think that would make the upload to OSSRH much more reliable.

1. The biggest "bang-for-the-buck" option would be to remove the embedded liberty zip and instead have the install script download that at install time.  However, that makes it less convenient because you need internet access to install.

2. Another option I've wanted to do for a while is to split our bulkdata stuff

3. Another idea I had is to use the maven-liberty-plugin to package our webapp:  https://github.com/OpenLiberty/ci.maven/blob/main/docs/package.md#package
   Today we basically do that work ourselves.  Hopefully wouldn't be too hard to use this more official mechanism and then, hopefully, we'd only be including the bits that are needed at runtime (vs the liberty-runtime zip which probably includes more).

**Comment by lmsurpre** [comment]
```$ du -sh *
152M	artifacts
8.0K	install.bat
4.0K	install.sh
300M	openliberty-runtime-22.0.0.8.zip
 47M	tools
```
```
$ du -sh artifacts/servers/defaultServer/apps/*
 50M	artifacts/servers/defaultServer/apps/fhir-bulkdata-webapp.war
580K	artifacts/servers/defaultServer/apps/fhir-openapi.war
 96M	artifacts/servers/defaultServer/apps/fhir-server.war
```

**Comment by lmsurpre** [comment]
I created #3935 from the above.  The process is working for now, so marking this one as closed.
