### ISSUE TITLE
Integration tests are flaky on windows

### ISSUE THREAD

**Issue by lmsurpre** [LinuxForHealth/FHIR#3888]
**Describe the bug**
I've noticed our windows workflow failing at about 5 minutes on a few occasions now.
It seemed to start on https://github.com/LinuxForHealth/FHIR/pull/3887 but I don't see how that could be related.

**Environment**
main (CI only)

**To Reproduce**
1. run the CI a lot

**Expected behavior**
tests should reliably pass or fail

**Additional context**
GraphTermServiceProviderTimeLimitTest sets a time limit of 1 millisecond for cassandra, then performs a query and expects that query to time out.  Its reliable on my machine, but its occasionally failing in the CI for some reason.

JDBCSortTest is failing because the windows-19 environment was assigning the same timestamp (microsecond granularity) to 5 of the 6 resources that get created for this test.  It never used to do that.

JDBCWholeSystemSearchTest is failing for a similar reason...one of the test cases searched by lastUpdated time and was expecting a single match (but was getting 2).

**Comment by lmsurpre** [comment]
The windows-2019 behavior is still pretty odd, but I've made changes to GraphTermServiceProviderTimeLimitTest and JDBCWholeSystemSearchTest to make them more robust.

For GraphTermServiceProviderTimeLimitTest, I just disabled it.

**Comment by punktilious** [comment]
For Windows, it's possible the JVM isn't using the hi-resolution (aka multimedia) clock...in which case it probably runs at 100 ticks/second (10ms ticks). It could be a limitation of the virtualization environment.

**Comment by lmsurpre** [comment]
Integration tests have been more stable on windows.  Considering this one done.
