### ISSUE TITLE
[FHIR] How to recover a deleted record?

### ISSUE THREAD

**Issue by cpeter0702** [LinuxForHealth/FHIR#3894]
hi LinuxForHealth,
How are you doing? I'm learning and implementing the FHIR server. There is a question about deleted record recovery. If you can provide a solution or any suggestion, I'll really appreciate it

There are two ways to delete a resource record. One is **normal delete** and the other one is **hard delete**.
	# **NORMAL DELETE:** [Delete] https://localhost:9443/fhir-server/api/Patient/17b4c9f9321-12696b6e-510e-4f83-aaa4-32bfd864fb73
	# **HARD DELETE:** [POST] https://localhost:9443/fhir-server/api/Patient/17b4c9f9321-12696b6e-510e-4f83-aaa4-32bfd864fb73/$erase 

	I think normal deletion is a kind of mark deletion because I can still find it by using **_history** command.
	A solution I'm thinking of is to GET the _history record first and then re-POST it. 
	However, I cannot keep the same ID in this way.
	I was wondering is there any way to recover a record that I just deleted?

Thanks again, and have a great one

**Comment by lmsurpre** [comment]
Hi @cpeter0702.  As you found, and per https://hl7.org/fhir/http.html, `POST [base]/[resourceType]` will create a new resource with a server-assigned id.

To "restore" a deleted resource, you will instead issue a PUT to `[base]/[resourceType]/[id]`.
https://hl7.org/fhir/http.html#update

**Comment by cpeter0702** [comment]
got it, I've tried it, and it works. Thanks for your help
