### ISSUE TITLE
[FHIR] How to ensure that the record in a resource is not duplicated?

### ISSUE THREAD

**Issue by cpeter0702** [LinuxForHealth/FHIR#3895]
hi LinuxForHealth,
How are you doing? I'm learning and implementing the FHIR server. There is a question about duplicated records avoiding. If you can provide a solution or any suggestion, I'll really appreciate it.

How to ensure that the record in a resource is not duplicated?
	I know the field ID in a resource is unique and represents a record.
	However, I'm looking for any other way to set a field that makes business sense as a unique judgment.
	Taking a resource Organization as an example, There is already a record of "Tufts Medical Center" in the database.
	Is there any way to avoid the next record having the same name? 
	I'm trying to find a way except for doing a GET action before the POST.

Thanks again, and have a great one

**Comment by lmsurpre** [comment]
Hi @cpeter0702.  There's a few ways to do that.

The mechanism defined by the FHIR specification is called [conditional create](https://hl7.org/fhir/http.html#ccreate).  Unfortunately, our implementation (and most others') can't provide absolute uniqueness guarantees if the creates are executed in parallel.

For cases where you need a stronger level of assurance, we have a special feature implemented for "conditional create-on-update".  This will only work in controlled environments where it is safe to use "client-assigned" resource ids.
In this case, if you pass the HTTP header `If-None-Match: *` then the server will perform the "update" only if the resource doesn't already exit.  See https://linuxforhealth.github.io/FHIR/Conformance#http-headers for more info.

**Comment by lmsurpre** [comment]
Worth mentioning:  both of the above options require the client to "do the right thing".  At the server level, its possible to write an [interceptor](https://linuxforhealth.github.io/FHIR/guides/FHIRServerUsersGuide#43-persistence-interceptors) to enforce whatever business logic you'd like.  So I guess that would be the way to ensure it at the server level.

**Comment by cpeter0702** [comment]
hi @lmsurpre, thank you so much for your reply. Using "conditional create-on-update" is helpful and solves my primary key issue. In addition,  because I also have needs to make one of the columns or fields unique other than the primary key,  I'm trying to implement the "interceptor". Thanks again, and have a great one.
