### ISSUE TITLE
Should rollback not commit after healthcheck connection error

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3941]
**Describe the bug**
If the `$healthcheck` operation encounters an invalid connection, we still end up attempting to commit the transaction instead of rolling back. We need a mechanism to trigger a rollback for certain OperationOutcomes. 

**Environment**
Which version of IBM FHIR Server? 5.0.0-RC2

**To Reproduce**
1. See details here: https://github.com/OpenLiberty/open-liberty/issues/20599

**Expected behavior**
Transactions should be rolled back not committed when an invalid connection is identified in the `$healthcheck` operation.

**Additional context**
This issue was identified by the Open Liberty team responding to https://github.com/OpenLiberty/open-liberty/issues/20599.

It's unclear at the moment if this is having any functional impact, so might just be better practice.

**Comment by lmsurpre** [comment]
Maybe we can change our `numConnectionsPerThreadLocal` setting from 0 to 1 or 2 after addressing this?!
