### ISSUE TITLE
wiki home page broken links

### ISSUE THREAD

**Issue by berkant-k** [LinuxForHealth/FHIR#3942]
**Describe the bug**
Wiki home page still referencing broken link such as (https://ibm.github.io/FHIR )

**Environment**
wiki 

**Expected behavior**
Broken link should be fixed. And also LinuxForHealth renaming needed.

**Comment by punktilious** [comment]
@berkant-k Thanks for letting us know. We're working our way through these rebrand issues and will endeavour to get this fixed for our next release/release candidate.

**Comment by lmsurpre** [comment]
I pushed an update to fix all the broken links and finish the renaming on the wiki.
