### ISSUE TITLE
wiki git clone is not working on Windows

### ISSUE THREAD

**Issue by berkant-k** [LinuxForHealth/FHIR#3943]
**Describe the bug**
Wiki repository  https://github.com/LinuxForHealth/FHIR.wiki.git  clone fails with  "error: invalid path" message.

**Environment**
git version 2.37.0.windows.1

**To Reproduce**
1. Open terminal
2. execute git clone https://github.com/LinuxForHealth/FHIR.wiki.git
3. See error
error: invalid path 'Image-and-Container:-Tips.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Expected behavior**
git clone should be work fine.

**Additional context**
Don't use the following characters in your wiki page's titles: \ / : * ? " < > |. Users on certain operating systems won't be able to work with filenames containing these characters. 
Check out this document  https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#about-wiki-filenames

**Comment by punktilious** [comment]
@berkant-k  thanks - we will get this one fixed too.

**Comment by punktilious** [comment]
@berkant-k I renamed the pages I think were the problem. Please try again and let me know how it goes.

**Comment by berkant-k** [comment]
Thanks. It is working now.
