### ISSUE TITLE
Schema size report does not appear to correctly filter schemas

### ISSUE THREAD

**Issue by punktilious** [LinuxForHealth/FHIR#3949]
**Describe the bug**
When adding a second schema, the size report appeared to include the size of the first schema.

**Environment**
Which version of LinuxForHealth FHIR Server? 5.0.0-RC2

**To Reproduce**
1. Create one schema with lots of data
2. Create a second schema without much data
3. Report the sizes of both, and notice that the size of the `small` schema is similar to the size of the `large` schema.

**Expected behavior**
The size report should accurately show the size of each schema

**Additional context**

Running the schema size report:

```
java -jar /path/to/fhir-persistence-schema/target/fhir-persistence-schema-*-cli.jar \
  --db-type postgresql \
  --prop-file fhiradmin.properties \
  --schema-name your-schema-name \
  --show-db-size \
  --show-db-size-detail
```

**Comment by lmsurpre** [comment]
maybe tackle #3872 at the same time?

**Comment by PrasannaHegde1** [comment]
Created the following 2 schemas. 
1. FHIRDATA with more data
2. FHIRTESTDATA with less data 
After running the schema size report, got the below details.
````
Database Size Report
====================
        Date: 2022-10-12T17:42:11.262836Z
      Schema: FHIRDATA
     Db Size:     37150720 bytes
  Table Size:     14893056 bytes
  Index Size:     22257664 bytes


  Database Size Report
====================
        Date: 2022-10-12T19:47:43.009443Z
      Schema: FHIRTESTDATA
     Db Size:     10240000 bytes
  Table Size:       630784 bytes
  Index Size:      9609216 bytes

````
Now the size report  accurately show the size of each schema. This is working as expected.
