### ISSUE TITLE
Intermediary server configuration

### ISSUE THREAD

**Issue by igorboss** [LinuxForHealth/FHIR#4060]
**Is your feature request related to a problem? Please describe.**
In our environment, we have 2 LFH servers (for clinical data and for scheduling and appointments), and 1 MPI app with its own FHIR implementation also. All three have different business owners. There are no intersections of resources - every app is responsible for its own resource. Currently, our users are informed where which resource they should query, but it creates problems from time to time. 
And we plan to add other servers, to support distributed processing of data.
We need the intermediary server to the front of these three servers to hide the complexity of the distributed system that should route queries to the proper server and aggregate searches.
The idea of the intermediary server is described in HL7 Confluence https://confluence.hl7.org/display/FHIR/Intermediaries+White+Paper.
A similar approach in SmileCDR is described on FHIR Gateway Configuration Document page https://smilecdr.com/docs/fhir_gateway/configuration_document.html.

**Describe the solution you'd like**
Please provide an example or reference to the documentation if an intermediary server or some gateway exists.

**Describe alternatives you've considered**
If such required functionality missing please provides a version in the server roadmap..

**Comment by lmsurpre** [comment]
We haven't done much on this and its not on our roadmap.
As an open source project, we'd be interested to hear your thoughts on it.
We'd be happy to offer feedback and guidance if someone presented a design or a pull request.

**Comment by igorboss** [comment]
Thank you.
