### ISSUE TITLE
POST / PUT requests have a delay of a minute to complete

### ISSUE THREAD

**Issue by renom** [LinuxForHealth/FHIR#4094]
**Describe the bug**
On the latest fhir server version POST and PUT requests hang for a minute before getting finished.

**Environment**
Linux, docker, postman. Tested on two different PCs, both have the latest version installed.

**To Reproduce**
Create or update a patient resource.

**Expected behavior**
Requests should complete way faster.

**Comment by renom** [comment]
Just figured out that's because fhir server is configured to send kafka notifications, but kafka was down. Now it works fine. Is it still relevant?

**Comment by lmsurpre** [comment]
Thanks @renom; I agree that delaying the transaction due to misconfigured / unresponsive kafka is not ideal.
I'll close this one, but we will consider this when we get to #3071.
