### ISSUE TITLE
Upgrade to liberty 22.0.0.12

### ISSUE THREAD

**Issue by PrasannaHegde1** [LinuxForHealth/FHIR#4116]
**Describe the bug**
Upgrade [openliberty-runtime](https://github.com/OpenLiberty/open-liberty) from 22.0.0.10 to 22.0.0.12.

**Environment**
Which version of LinuxForHealth FHIR Server? 5.1

**Comment by lmsurpre** [comment]
I deployed to a cluster on ibm cloud, confirmed it was running on openliberty 22.0.0.12, and successfully executed the touchstone basic tests against it... all tests passing.
