### ISSUE TITLE
FHIRProvider: Element clinicalStatus does not contain a Coding element with a valid system and code combination (Condition)

### ISSUE THREAD

**Issue by kidus-tiliksew** [LinuxForHealth/FHIR#4179]
**Describe the bug**

I'm getting this error when trying to create a new Condition resource with just the following payload 

`
    {
         resourceType: "Condition",
         clinicalStatus: {
             coding: [
                 {
                      code: "active",
                      display: "Active",
                      system: "http://hl7.org/fhir/ValueSet/condition-clinical"
                  }
             ]
         }
    }
`

Active is valid input for clinicalStatus

**Environment**
Version 5.1.1

**Comment by lmsurpre** [comment]
according to https://hl7.org/fhir/valueset-condition-clinical.html the proper system for this one is [http://terminology.hl7.org/CodeSystem/condition-clinical](https://hl7.org/fhir/codesystem-condition-clinical.html)

**Comment by kidus-tiliksew** [comment]
Yup I've tried it with that too but I get the same error
