### ISSUE TITLE
Is there any way to generate a div value of the text element for each resource?

### ISSUE THREAD

**Issue by cpeter0702** [LinuxForHealth/FHIR#4197]
Hi LinuxForHealth,
How are you doing? Is there any way to generate a div value of the text element for each resource?

Because most resources extend from DomainResource, there is a text element with a Narrative type for representing the content of the resource to a human. Do I have to generate the value in XHTML format by myself based on the content of the resource? I was wondering is there any way or util program that can automatically generate XHTML content? I didn't find a relevant solution on the Internet. If you can give me a suggestion, I would be very grateful. Thanks again, and have a great one.

Sincerely,

Peter Liao

**Comment by lmsurpre** [comment]
Hi @cpeter0702 , sorry I missed this one.

We actually did introduce a helper method for just this:  https://linuxforhealth.github.io/FHIR/javadocs/latest/org/linuxforhealth/fhir/model/type/Xhtml.html#from(java.lang.String)

Please let us know if that is what you were looking for or if you had something else in mind.

**Comment by cpeter0702** [comment]
hi Imsurpre, 
I really appreciate your willingness to take the time to answer my question. I just tried out the from method of Xhtml, and it works very well. Thank you so much and have a great one.
