### ISSUE TITLE
not finding trust default Certs in server.xml Can you specify the location of server.xml file 

### ISSUE THREAD

**Issue by ryadav007** [LinuxForHealth/FHIR#4212]
Confirmed successful lookup on SNOMED-CT
---
---
added the following to fhir-server-config.json (same level as "core"):

        "term": {
             "remoteTermServiceProviders": [{
                "__comment": "Configuration for public SNOMED-CT endpoint",
                "enabled": true,
                "base": "https://snowstorm-fhir.snomedtools.org/fhir",
                "supports": [{
                    "system": "http://snomed.info/sct"
                }]
            }]
        },
		
added trustDefaultCerts="true" to server.xml:

<ssl clientAuthenticationSupported="true" id="defaultSSLConfig" keyStoreRef="defaultKeyStore" sslProtocol="TLSv1.2" trustStoreRef="defaultTrustStore" trustDefaultCerts="true"/>
		

GET  https://localhost:9443/fhir-server/api/v4/CodeSystem/$lookup?system=http://snomed.info/sct&code=195967001

_Originally posted by @kmbarton423 in https://github.com/LinuxForHealth/FHIR/issues/2198#issuecomment-825162378_

**Comment by ryadav007** [comment]
cannot find the server.xml in the directory structure 
1)/usr/server/defaultServer/server.xml
2)fhir-installer/liberty-runtime/wlp2/templates/servers/defaultServer/server.xml

**Comment by lmsurpre** [comment]
are you using the docker image or installing the server yourself?

on the docker image, i believe the server.xml can be found at `/opt/ol/wlp/usr/servers/defaultServer/server.xml`

we should probably add that to the user's guide... currently it just uses the <WLP_BASE> placeholder in most places (and in one place still has the old `/opt/ibm` path)

**Comment by ryadav007** [comment]
th
