### ISSUE TITLE
Multi-tenancy: Users from a tenant can read data belongs to other tenants

### ISSUE THREAD

**Issue by quickbeard** [LinuxForHealth/FHIR#4226]
**Describe the bug**
It seems like in multi-tenancy environment, users from a particular tenant can actually access data belongs to other tenants.

**Environment**
LFH FHIR Helm chart 0.9.1

**Expected behavior**
Users from a particular tenant should not be able to access data from other tenants.

**Comment by lmsurpre** [comment]
Can you provide more information?
If its sensitive in nature, feel free to direct message me on chat.fhir.org

**Comment by quickbeard** [comment]
> Can you provide more information? If its sensitive in nature, feel free to direct message me on chat.fhir.org

Resolved by using multiple databases. Thanks!
