### ISSUE TITLE
fhir server app error

### ISSUE THREAD

**Issue by gavin8051** [LinuxForHealth/FHIR#4246]
I would like to inquire about an error that suddenly appeared in my IBM FHIR Server:
1.E com.ibm.ws.webcontainer.webapp.WebApp handleRequest SRVE0315E: An exception occurred: java.lang.Throwable: javax.servlet.ServletException: Filter [FHIRRestFilter]: could not be initialized
2.Caused by: jakarta.json.stream.JsonParsingException: Invalid token=EOF at (line no=161, column no=5030, offset=11636). Expected tokens are: [COMMA, CURLYCLOSE]
Can anyone suggest any modifications or adjustments that can be made to address this issue?

**Comment by berkant-k** [comment]
Could you provide more details about your request? Which endpoint are you referring to, or what is the payload?

**Comment by gavin8051** [comment]
I later identified the issue. Due to problems with my configuration file modifications, I subsequently downloaded a new server configuration, and after making adjustments, it is now functioning properly. Thank you
